version: '3.9'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PORT: ${PORT}
    environment:
      PORT: ${PORT}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${PORT}:${PORT} # Прокидываем порт для доступа к Node.js серверу
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432" # Прокидываем порт для доступа к PostgreSQL
    volumes:
      - ./data:/var/lib/postgresql/data # Используем локальный путь вместо volume