version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: 5000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thread
    ports:
      - "5000:5000" # Прокидываем порт для доступа к Node.js серверу
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: thread
    ports:
      - "5432:5432" # Прокидываем порт для доступа к PostgreSQL
    volumes:
      - ./data:/var/lib/postgresql/data # Используем локальный путь вместо volume